name: NuGet Windows build

on: [push, pull_request]

jobs:

  windows-msvc-debug:
    runs-on: "windows-latest"
    steps:
    - uses: actions/checkout@v2
    - name: Configure
      run:  cmake -G "Visual Studio 17 2022" -A Win32 -S .
    - name: Build
      run: |
        cmake --build . --config "Debug"
        tree /a /f .
    - name: Test
      run: ctest -VV -C "Debug"
    - name: Upload artifact
      uses: actions/upload-artifact@v2.2.4
      with:
        name: windows-msvc-debug
        path: Debug/*
      
  windows-msvc-release:
    runs-on: "windows-latest"
    steps:
    - uses: actions/checkout@v2
    - name: Configure
      run:  cmake -G "Visual Studio 17 2022" -A Win32 -S .
    - name: Build
      run: |
        cmake --build . --config "Release"
        tree /a /f .
    - name: Test
      run: ctest -VV -C "Release"
    - name: Upload artifact
      uses: actions/upload-artifact@v2.2.4
      with:
        name: windows-msvc-release
        path: Release/*
  
  nuget-package:
    needs: [windows-msvc-release, windows-msvc-debug]
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Download all Build Artifacts
      uses: actions/download-artifact@v2.0.10
    - name: Move files to correct directories
      shell: pwsh
      run: |
        dir
        mkdir Debug
        mkdir Release
        move windows-msvc-debug\* Debug\
        move windows-msvc-release\* Release\
        move src\zip.h zip.h
        
    - name: Create NuGet package
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: nuget pack zip.nuspec

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.3
      with:
        # Artifact name
        name: NuGet package # optional, default is artifact
        # A file, directory or wildcard pattern that describes what to upload
        path: "*.nupkg"
    - name: Set up NuGet source
      run: nuget sources add -Source https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json -Name github -Username ${{ github.repository_owner }} -Password ${{ github.token }} -StorePasswordInClearText
    - name: Publish NuGet to GitHub registry
      run: nuget push *.nupkg -Source github -NoSymbols 
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}     
